import Head from 'next/head'

import { Heading } from 'common/heading';

export default function Profile() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading as="h1">Dit is de profile page, je bent ingelogged</Heading>
    </div>
  )
}