import Head from 'next/head'
import styled from "styled-components";

const Heading = styled.h1`
  color: red;
  font-size: 24px;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>dit is de home page</Heading>
    </div>
  )
}
